---
all:
  children:

    switches:
      children:

        cisco_switches:
          children:

            cisco_ios_switches:
              hosts:

                iol-l2:
                  ansible_host: 10.10.20.101
                  
                cat9000v:
                  ansible_host: 10.10.20.102
